# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 2.3.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/saipaisi/uploadPath，Linux配置 /home/saipaisi/uploadPath）
  profile: /home/saipaisi/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8081
  port: 10888
  servlet:
    # 应用的访问路径
    context-path: /prod-api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.saipaisi: debug
    org.springframework: warn
    com.saipaisi.project.basic.fegin: debug

# Spring配置
spring:

  #liquibase
  liquibase:
    change-log: classpath:liquibase/master.xml
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size: 100MB
       # 设置总上传的文件大小
       max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置


# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认10个小时）
    expireTime: 10
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.saipaisi.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

callback:
  url: http://crm.saipaisi.cn/prod-api/

tanyancha:
  url: http://open.api.tianyancha.com/

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
# 代码生成
gen: 
  # 作者
  author: saipaisi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.saipaisi.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
qxinbao:
  prod-url: http://api.qixin.com/APIService
  test-url: http://api.qixin.com/APITestService
  appkey: 9b69701d-c175-4419-8e28-5438f10774b0
  secret_key: 3a14c85e-61ec-4639-8b69-eca3b00abba3